apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: developer
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - create
  - delete
